function symbolicExpression = default_ODE_v_1_1_fun_1(t,in2,in3)
%default_ODE_v_1_1_fun_1
%    symbolicExpression = default_ODE_v_1_1_fun_1(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:42:00

varODEs1 = in3(:,1);
symbolicExpression = sparse([1],[1],[varODEs1],4,1);
end
