function symbolicExpression = default_ODE_t_fun_1(t,in2,in3)
%default_ODE_t_fun_1
%    symbolicExpression = default_ODE_t_fun_1(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:41:59

parameters1 = in2(1,:);
parameters2 = in2(2,:);
parameters3 = in2(3,:);
parameters4 = in2(4,:);
varODEs1 = in3(:,1);
varODEs2 = in3(:,2);
varODEs3 = in3(:,3);
symbolicExpression = sparse([1,2,3,4],[1,1,1,1],[parameters1.*varODEs1,parameters2.*varODEs2,parameters3.*varODEs2,parameters4.*varODEs3],4,1);
end
