function symbolicExpression = default_t_fun_1(t,in2)
%DEFAULT_T_FUN_1
%    symbolicExpression = DEFAULT_T_FUN_1(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:12:55

symbolicExpression = sparse([1,2],[1,1],[1.0,1.0],2,1);
end
