function symbolicExpression = default_1_fun_1(in1,in2)
%DEFAULT_1_FUN_1
%    symbolicExpression = DEFAULT_1_FUN_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:12:55

parameters1 = in2(1,:);
states2 = in1(2,:);
symbolicExpression = parameters1.*states2;
end
