function symbolicExpression = default_1_1_fun_1(in1,in2)
%DEFAULT_1_1_FUN_1
%    symbolicExpression = DEFAULT_1_1_FUN_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:41:58

states1 = in1(1,:);
symbolicExpression = states1;
end
