function symbolicExpression = default_ODE_s_fun_1(in1,in2,in3)
%default_ODE_s_fun_1
%    symbolicExpression = default_ODE_s_fun_1(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:41:59

symbolicExpression = sparse([],[],[],4,4);
end
