function symbolicExpression = default_2_fun_1(in1,in2)
%DEFAULT_2_FUN_1
%    symbolicExpression = DEFAULT_2_FUN_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:41:58

parameters2 = in2(2,:);
states2 = in1(2,:);
symbolicExpression = parameters2.*states2;
end
