function symbolicExpression = default_3_3_fun_1(in1,in2)
%DEFAULT_3_3_FUN_1
%    symbolicExpression = DEFAULT_3_3_FUN_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:41:58

states2 = in1(2,:);
symbolicExpression = states2;
end
