function symbolicExpression = default_v_1_1_fun_1(t,in2)
%DEFAULT_V_1_1_FUN_1
%    symbolicExpression = DEFAULT_V_1_1_FUN_1(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:12:55

symbolicExpression = sparse([],[],[],2,1);
end
