function symbolicExpression = default_4_4_fun_1(in1,in2)
%DEFAULT_4_4_FUN_1
%    symbolicExpression = DEFAULT_4_4_FUN_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:41:59

states3 = in1(3,:);
symbolicExpression = states3;
end
