function symbolicExpression = default_s_fun_1(in1,in2)
%DEFAULT_S_FUN_1
%    symbolicExpression = DEFAULT_S_FUN_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:12:55

states1 = in1(1,:);
states2 = in1(2,:);
symbolicExpression = reshape([states2,0.0,0.0,states1],[2,2]);
end
