function symbolicExpression = default_1_1_fun_1(in1,in2)
%DEFAULT_1_1_FUN_1
%    symbolicExpression = DEFAULT_1_1_FUN_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:12:55

states2 = in1(2,:);
symbolicExpression = states2;
end
