function symbolicExpression = default_ODE_t_fun_1(t,in2,in3)
%default_ODE_t_fun_1
%    symbolicExpression = default_ODE_t_fun_1(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:12:56

parameters1 = in2(1,:);
parameters2 = in2(2,:);
varODEs1 = in3(:,1);
varODEs2 = in3(:,2);
symbolicExpression = sparse([1,2],[1,1],[parameters1.*varODEs2,parameters2.*varODEs1],2,1);
end
