function symbolicExpression = default_ODE_2_1_fun_1(in1,in2,in3)
%default_ODE_2_1_fun_1
%    symbolicExpression = default_ODE_2_1_fun_1(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:12:56

symbolicExpression = sparse(0.0);
end
