function symbolicExpression = default_2_fun_1(in1,in2)
%DEFAULT_2_FUN_1
%    symbolicExpression = DEFAULT_2_FUN_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:12:55

parameters2 = in2(2,:);
states1 = in1(1,:);
symbolicExpression = parameters2.*states1;
end
