function symbolicExpression = default_3_4_fun_1(in1,in2)
%DEFAULT_3_4_FUN_1
%    symbolicExpression = DEFAULT_3_4_FUN_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:41:59

symbolicExpression = 0.0;
end
