function symbolicExpression = default_ODE_dt_fun_1(t,in2,in3)
%default_ODE_dt_fun_1
%    symbolicExpression = default_ODE_dt_fun_1(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:12:56

parameters1 = in2(1,:);
parameters2 = in2(2,:);
symbolicExpression = sparse([2,1],[1,2],[parameters2,parameters1],2,2);
end
