function symbolicExpression = default_x_fun_1(in1,in2)
%DEFAULT_X_FUN_1
%    symbolicExpression = DEFAULT_X_FUN_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:41:58

parameters1 = in2(1,:);
parameters2 = in2(2,:);
parameters3 = in2(3,:);
parameters4 = in2(4,:);
states1 = in1(1,:);
states2 = in1(2,:);
states3 = in1(3,:);
symbolicExpression = [parameters1.*states1;parameters2.*states2;parameters3.*states2;parameters4.*states3];
end
