function symbolicExpression = default_ODE_v_1_2_fun_1(t,in2,in3)
%default_ODE_v_1_2_fun_1
%    symbolicExpression = default_ODE_v_1_2_fun_1(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:12:56

varODEs1 = in3(:,1);
symbolicExpression = sparse([2],[1],[varODEs1],2,1);
end
