function symbolicExpression = default_1_fun_1(in1,in2)
%DEFAULT_1_FUN_1
%    symbolicExpression = DEFAULT_1_FUN_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:41:58

parameters1 = in2(1,:);
states1 = in1(1,:);
symbolicExpression = parameters1.*states1;
end
