function symbolicExpression = Model_FSP_dOpt_ODE_x_fun_1(in1,in2,in3)
%Model_FSP_dOpt_ODE_x_fun_1
%    symbolicExpression = Model_FSP_dOpt_ODE_x_fun_1(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    27-Feb-2026 13:39:48

symbolicExpression = sparse([1,2,3,4],[1,1,1,1],[1.0,1.0,1.0,1.0],4,1);
end
