function symbolicExpression = Model_FSP_dOpt_ODE_2_fun_1(in1,in2)
%Model_FSP_dOpt_ODE_2_fun_1
%    symbolicExpression = Model_FSP_dOpt_ODE_2_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    04-Feb-2026 23:18:27

symbolicExpression = 1.0;
end
