function symbolicExpression = Model_ODE_x_fun_1(states1,in2)
%Model_ODE_x_fun_1
%    symbolicExpression = Model_ODE_x_fun_1(STATES1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 13:45:05

parameters2 = in2(2,:);
symbolicExpression = [1.0;parameters2.*states1];
end
