function symbolicExpression = Model_ODE_2_1_fun_1(states1,in2)
%Model_ODE_2_1_fun_1
%    symbolicExpression = Model_ODE_2_1_fun_1(STATES1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    15-Feb-2026 20:15:52

symbolicExpression = 1.0;
end
