function symbolicExpression = Model_ODE_ODE_4_3_fun_1(in1,in2,in3)
%Model_ODE_ODE_4_3_fun_1
%    symbolicExpression = Model_ODE_ODE_4_3_fun_1(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:41:04

symbolicExpression = sparse(0.0);
end
