function symbolicExpression = Model_ODE_ODE_v_1_3_fun_1(t,in2,in3)
%Model_ODE_ODE_v_1_3_fun_1
%    symbolicExpression = Model_ODE_ODE_v_1_3_fun_1(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:41:05

varODEs2 = in3(:,2);
symbolicExpression = sparse([3],[1],[varODEs2],4,1);
end
