function symbolicExpression = Model_sens_2_2_x_fun_1(states1,in2)
%Model_sens_2_2_x_fun_1
%    symbolicExpression = Model_sens_2_2_x_fun_1(STATES1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    28-Jan-2026 14:51:03

symbolicExpression = [1.0;1.0];
end
