function symbolicExpression = Model_ODE_ODE_x_fun_1(in1,in2,varODEs1)
%Model_ODE_ODE_x_fun_1
%    symbolicExpression = Model_ODE_ODE_x_fun_1(IN1,IN2,varODEs1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 13:45:05

symbolicExpression = sparse([1,2],[1,1],[1.0,1.0],2,1);
end
