function symbolicExpression = Model_ODE_v_1_2_fun_1(t,in2)
%Model_ODE_v_1_2_fun_1
%    symbolicExpression = Model_ODE_v_1_2_fun_1(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:41:03

symbolicExpression = sparse([],[],[],4,1);
end
