function symbolicExpression = Model_SSA_2_2_fun_1(states1,in2)
%Model_SSA_2_2_fun_1
%    symbolicExpression = Model_SSA_2_2_fun_1(STATES1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    02-Feb-2026 16:51:45

symbolicExpression = states1;
end
