function symbolicExpression = Model_SSA_ODE_v_1_2_fun_1(t,in2,varODEs1)
%Model_SSA_ODE_v_1_2_fun_1
%    symbolicExpression = Model_SSA_ODE_v_1_2_fun_1(T,IN2,varODEs1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    02-Feb-2026 16:51:45

symbolicExpression = sparse([2],[1],[varODEs1],2,1);
end
