function symbolicExpression = Model_SSA_v_1_2_fun_1(t,in2)
%Model_SSA_v_1_2_fun_1
%    symbolicExpression = Model_SSA_v_1_2_fun_1(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    02-Feb-2026 16:51:45

symbolicExpression = sparse([],[],[],2,1);
end
