function symbolicExpression = Model_FSP_example_ODE_dt_fun_1(t,in2,in3)
%Model_FSP_example_ODE_dt_fun_1
%    symbolicExpression = Model_FSP_example_ODE_dt_fun_1(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:43:25

parameters1 = in2(1,:);
parameters2 = in2(2,:);
parameters3 = in2(3,:);
parameters4 = in2(4,:);
symbolicExpression = sparse([1,2,3,4],[1,2,2,3],[parameters1,parameters2,parameters3,parameters4],4,3);
end
