function symbolicExpression = Model_FSP_2_1_fun_1(states1,in2)
%Model_FSP_2_1_fun_1
%    symbolicExpression = Model_FSP_2_1_fun_1(STATES1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    03-Feb-2026 15:35:27

symbolicExpression = 1.0;
end
