function symbolicExpression = Model_ODE_2_ODE_2_fun_1(in1,in2)
%Model_ODE_2_ODE_2_fun_1
%    symbolicExpression = Model_ODE_2_ODE_2_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    24-Feb-2026 13:33:31

symbolicExpression = 1.0;
end
