function symbolicExpression = Model_sens_2_2_ODE_dt_fun_1(t,in2,varODEs1)
%Model_sens_2_2_ODE_dt_fun_1
%    symbolicExpression = Model_sens_2_2_ODE_dt_fun_1(T,IN2,varODEs1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    28-Jan-2026 14:51:03

symbolicExpression = sparse([],[],[],2,1);
end
