function symbolicExpression = Model_FSP_dOpt_2_fun_1(states1,in2)
%Model_FSP_dOpt_2_fun_1
%    symbolicExpression = Model_FSP_dOpt_2_fun_1(STATES1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    19-Feb-2026 01:53:59

parameters2 = in2(2,:);
symbolicExpression = parameters2.*states1;
end
