function symbolicExpression = Model_ODE_2_ODE_1_fun_1(in1,in2)
%Model_ODE_2_ODE_1_fun_1
%    symbolicExpression = Model_ODE_2_ODE_1_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    19-Feb-2026 01:53:59

symbolicExpression = 1.0;
end
