function symbolicExpression = Model_SSA_ODE_x_fun_1(in1,in2,varODEs1)
%Model_SSA_ODE_x_fun_1
%    symbolicExpression = Model_SSA_ODE_x_fun_1(IN1,IN2,varODEs1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    02-Feb-2026 16:51:45

symbolicExpression = sparse([1,2],[1,1],[1.0,1.0],2,1);
end
