function symbolicExpression = Model_FSP_example_t_fun_1(t,in2)
%Model_FSP_example_t_fun_1
%    symbolicExpression = Model_FSP_example_t_fun_1(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:43:24

symbolicExpression = sparse([1,2,3,4],[1,1,1,1],[1.0,1.0,1.0,1.0],4,1);
end
