function symbolicExpression = Model_ODE_s_fun_1(in1,in2)
%Model_ODE_s_fun_1
%    symbolicExpression = Model_ODE_s_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:41:03

states1 = in1(1,:);
states2 = in1(2,:);
states3 = in1(3,:);
symbolicExpression = reshape([states1,0.0,0.0,0.0,0.0,states2,0.0,0.0,0.0,0.0,states2,0.0,0.0,0.0,0.0,states3],[4,4]);
end
