function symbolicExpression = Model_ODE_t_fun_1(t,in2)
%Model_ODE_t_fun_1
%    symbolicExpression = Model_ODE_t_fun_1(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 13:45:05

parameters1 = in2(1,:);
symbolicExpression = sparse([1,2],[1,1],[parameters1,1.0],2,1);
end
