function symbolicExpression = Model_ODE_2_2_fun_1(states1,in2)
%Model_ODE_2_2_fun_1
%    symbolicExpression = Model_ODE_2_2_fun_1(STATES1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    18-Feb-2026 13:25:35

parameters2 = in2(2,:);
symbolicExpression = parameters2.*states1;
end
