function symbolicExpression = Model_FSP_dOpt_ODE_dt_fun_1(t,in2,varODEs1)
%Model_FSP_dOpt_ODE_dt_fun_1
%    symbolicExpression = Model_FSP_dOpt_ODE_dt_fun_1(T,IN2,varODEs1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    04-Feb-2026 23:18:27

parameters2 = in2(2,:);
symbolicExpression = sparse([2],[1],[parameters2],2,1);
end
