function symbolicExpression = Model_ODE_2_t_fun_1(t,in2)
%Model_ODE_2_t_fun_1
%    symbolicExpression = Model_ODE_2_t_fun_1(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    15-Feb-2026 20:15:52

parameters1 = in2(1,:);
symbolicExpression = sparse([1,2],[1,1],[parameters1,1.0],2,1);
end
