function symbolicExpression = Model_FSP_dOpt_2_fun_1(in1,in2)
%Model_FSP_dOpt_2_fun_1
%    symbolicExpression = Model_FSP_dOpt_2_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    27-Feb-2026 13:39:48

parameters2 = in2(2,:);
states2 = in1(2,:);
symbolicExpression = parameters2.*states2;
end
