function symbolicExpression = Model_FSP_dOpt_4_fun_1(in1,in2)
%Model_FSP_dOpt_4_fun_1
%    symbolicExpression = Model_FSP_dOpt_4_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    27-Feb-2026 13:39:48

parameters4 = in2(4,:);
states3 = in1(3,:);
symbolicExpression = parameters4.*states3;
end
