function symbolicExpression = Model_FSP_example_3_fun_1(in1,in2)
%Model_FSP_example_3_fun_1
%    symbolicExpression = Model_FSP_example_3_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:43:24

parameters3 = in2(3,:);
states2 = in1(2,:);
symbolicExpression = parameters3.*states2;
end
