function symbolicExpression = Model_ODE_1_fun_1(in1,in2)
%Model_ODE_1_fun_1
%    symbolicExpression = Model_ODE_1_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:41:02

parameters1 = in2(1,:);
states1 = in1(1,:);
symbolicExpression = parameters1.*states1;
end
