function symbolicExpression = Model_ODE_2_2_fun_1(states1,in2)
%Model_ODE_2_2_fun_1
%    symbolicExpression = Model_ODE_2_2_fun_1(STATES1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    04-Feb-2026 23:43:24

parameters2 = in2(2,:);
symbolicExpression = parameters2.*states1;
end
