function symbolicExpression = Model_SSA_ODE_t_fun_1(t,in2,varODEs1)
%Model_SSA_ODE_t_fun_1
%    symbolicExpression = Model_SSA_ODE_t_fun_1(T,IN2,varODEs1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    02-Feb-2026 16:51:45

parameters1 = in2(1,:);
parameters2 = in2(2,:);
symbolicExpression = sparse([1,2],[1,1],[parameters1,parameters2.*varODEs1],2,1);
end
