function symbolicExpression = RepressilatorGenes_ODE_1_5_fun_1(in1,in2,in3)
%RepressilatorGenes_ODE_1_5_fun_1
%    symbolicExpression = RepressilatorGenes_ODE_1_5_fun_1(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:40:47

symbolicExpression = sparse(0.0);
end
