function symbolicExpression = RepressilatorGenes_5_3_fun_1(in1,in2)
%RepressilatorGenes_5_3_fun_1
%    symbolicExpression = RepressilatorGenes_5_3_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:02:42

states4 = in1(4,:);
states9 = in1(9,:);
symbolicExpression = (states4.*states9.*(states9-1.0).*(states9-2.0))./1.2e+1;
end
