function symbolicExpression = RepressilatorGenes_ODE_v_1_2_fun_1(t,in2,in3)
%RepressilatorGenes_ODE_v_1_2_fun_1
%    symbolicExpression = RepressilatorGenes_ODE_v_1_2_fun_1(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:02:47

varODEs1 = in3(:,1);
varODEs4 = in3(:,4);
varODEs7 = in3(:,7);
symbolicExpression = sparse([3,7,11],[1,1,1],[varODEs1,varODEs4,varODEs7],12,1);
end
