function symbolicExpression = RepressilatorGenes_ODE_8_fun_1(in1,in2)
%RepressilatorGenes_ODE_8_fun_1
%    symbolicExpression = RepressilatorGenes_ODE_8_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:02:44

symbolicExpression = 1.0;
end
