function symbolicExpression = RepressilatorGenes_3_1_fun_1(in1,in2)
%RepressilatorGenes_3_1_fun_1
%    symbolicExpression = RepressilatorGenes_3_1_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:02:42

states2 = in1(2,:);
symbolicExpression = states2;
end
