function symbolicExpression = RepressilatorGenes_ODE_v_1_5_fun_1(t,in2,in3)
%RepressilatorGenes_ODE_v_1_5_fun_1
%    symbolicExpression = RepressilatorGenes_ODE_v_1_5_fun_1(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:02:47

varODEs3 = in3(:,3);
varODEs6 = in3(:,6);
varODEs9 = in3(:,9);
symbolicExpression = sparse([4,8,12],[1,1,1],[varODEs3,varODEs6,varODEs9],12,1);
end
