function symbolicExpression = RepressilatorGenes_11_fun_1(in1,in2)
%RepressilatorGenes_11_fun_1
%    symbolicExpression = RepressilatorGenes_11_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:02:41

parameters1 = in2(1,:);
parameters2 = in2(2,:);
states7 = in1(7,:);
states8 = in1(8,:);
symbolicExpression = parameters1.*states8+parameters2.*states7;
end
