function symbolicExpression = RepressilatorGenes_11_2_fun_1(in1,in2)
%RepressilatorGenes_11_2_fun_1
%    symbolicExpression = RepressilatorGenes_11_2_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:40:45

states7 = in1(7,:);
symbolicExpression = states7;
end
