function symbolicExpression = RepressilatorGenes_3_fun_1(in1,in2)
%RepressilatorGenes_3_fun_1
%    symbolicExpression = RepressilatorGenes_3_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:02:41

parameters1 = in2(1,:);
parameters2 = in2(2,:);
states1 = in1(1,:);
states2 = in1(2,:);
symbolicExpression = parameters1.*states2+parameters2.*states1;
end
