function symbolicExpression = RepressilatorGenes_ODE_v_1_3_fun_1(t,in2,in3)
%RepressilatorGenes_ODE_v_1_3_fun_1
%    symbolicExpression = RepressilatorGenes_ODE_v_1_3_fun_1(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:40:49

varODEs1 = in3(:,1);
varODEs3 = in3(:,3);
varODEs4 = in3(:,4);
varODEs6 = in3(:,6);
varODEs7 = in3(:,7);
varODEs9 = in3(:,9);
symbolicExpression = sparse([1,5,9],[1,1,1],[(varODEs1.*varODEs6.*(varODEs6-1.0).*(varODEs6-2.0))./1.2e+1,(varODEs4.*varODEs9.*(varODEs9-1.0).*(varODEs9-2.0))./1.2e+1,(varODEs3.*varODEs7.*(varODEs3-1.0).*(varODEs3-2.0))./1.2e+1],12,1);
end
