function symbolicExpression = RepressilatorGenes_v_1_3_fun_1(t,in2)
%RepressilatorGenes_v_1_3_fun_1
%    symbolicExpression = RepressilatorGenes_v_1_3_fun_1(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:02:43

symbolicExpression = sparse([],[],[],12,1);
end
