function symbolicExpression = RepressilatorGenes_ODE_dt_fun_1(t,in2,in3)
%RepressilatorGenes_ODE_dt_fun_1
%    symbolicExpression = RepressilatorGenes_ODE_dt_fun_1(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:02:45

parameters1 = in2(1,:);
parameters2 = in2(2,:);
parameters3 = in2(3,:);
parameters4 = in2(4,:);
parameters5 = in2(5,:);
varODEs1 = in3(:,1);
varODEs3 = in3(:,3);
varODEs4 = in3(:,4);
varODEs6 = in3(:,6);
varODEs7 = in3(:,7);
varODEs9 = in3(:,9);
t2 = varODEs3-1.0;
t4 = varODEs6-1.0;
t6 = varODEs9-1.0;
t3 = t2-1.0;
t5 = t4-1.0;
t7 = t6-1.0;
mt1 = sparse([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,3,14,15,28,33,41,43,54,55,61,68,81,83,94,95],[(parameters3.*t4.*t5.*varODEs6)./1.2e+1,parameters2,parameters4,parameters1,parameters5,(parameters3.*t2.*t3.*varODEs7)./1.2e+1+(parameters3.*t2.*varODEs3.*varODEs7)./1.2e+1+(parameters3.*t3.*varODEs3.*varODEs7)./1.2e+1,(parameters3.*t6.*t7.*varODEs9)./1.2e+1,parameters2,parameters4,parameters1,(parameters3.*t4.*t5.*varODEs1)./1.2e+1+(parameters3.*t4.*varODEs1.*varODEs6)./1.2e+1+(parameters3.*t5.*varODEs1.*varODEs6)./1.2e+1,parameters5,(parameters3.*t2.*t3.*varODEs3)./1.2e+1,parameters2,parameters4,parameters1],1,100);
mt2 = sparse([1,1],[1,8],[(parameters3.*t6.*t7.*varODEs4)./1.2e+1+(parameters3.*t6.*varODEs4.*varODEs9)./1.2e+1+(parameters3.*t7.*varODEs4.*varODEs9)./1.2e+1,parameters5],1,8);
symbolicExpression = reshape([mt1,mt2],12,9);
end
