function symbolicExpression = RepressilatorGenes_x_fun_1(in1,in2)
%RepressilatorGenes_x_fun_1
%    symbolicExpression = RepressilatorGenes_x_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:02:41

parameters1 = in2(1,:);
parameters2 = in2(2,:);
parameters3 = in2(3,:);
parameters4 = in2(4,:);
parameters5 = in2(5,:);
states1 = in1(1,:);
states2 = in1(2,:);
states3 = in1(3,:);
states4 = in1(4,:);
states5 = in1(5,:);
states6 = in1(6,:);
states7 = in1(7,:);
states8 = in1(8,:);
states9 = in1(9,:);
symbolicExpression = [(parameters3.*states1.*states6.*(states6-1.0).*(states6-2.0))./1.2e+1;parameters4.*states2;parameters1.*states2+parameters2.*states1;parameters5.*states3;(parameters3.*states4.*states9.*(states9-1.0).*(states9-2.0))./1.2e+1;parameters4.*states5;parameters1.*states5+parameters2.*states4;parameters5.*states6;(parameters3.*states3.*states7.*(states3-1.0).*(states3-2.0))./1.2e+1;parameters4.*states8;parameters1.*states8+parameters2.*states7;parameters5.*states9];
end
