function symbolicExpression = RepressilatorGenes_9_3_fun_1(in1,in2)
%RepressilatorGenes_9_3_fun_1
%    symbolicExpression = RepressilatorGenes_9_3_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:40:45

states3 = in1(3,:);
states7 = in1(7,:);
symbolicExpression = (states3.*states7.*(states3-1.0).*(states3-2.0))./1.2e+1;
end
