function symbolicExpression = RepressilatorGenes_ODE_4_2_fun_1(in1,in2,in3)
%RepressilatorGenes_ODE_4_2_fun_1
%    symbolicExpression = RepressilatorGenes_ODE_4_2_fun_1(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:02:45

symbolicExpression = sparse(0.0);
end
