function symbolicExpression = RepressilatorGenes_1_fun_1(in1,in2)
%RepressilatorGenes_1_fun_1
%    symbolicExpression = RepressilatorGenes_1_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:02:40

parameters3 = in2(3,:);
states1 = in1(1,:);
states6 = in1(6,:);
symbolicExpression = (parameters3.*states1.*states6.*(states6-1.0).*(states6-2.0))./1.2e+1;
end
