function symbolicExpression = RepressilatorGenes_t_fun_1(t,in2)
%RepressilatorGenes_t_fun_1
%    symbolicExpression = RepressilatorGenes_t_fun_1(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:40:43

symbolicExpression = sparse([1,2,3,4,5,6,7,8,9,10,11,12],[1,1,1,1,1,1,1,1,1,1,1,1],[1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0],12,1);
end
