function symbolicExpression = RepressilatorGenes_2_fun_1(in1,in2)
%RepressilatorGenes_2_fun_1
%    symbolicExpression = RepressilatorGenes_2_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:02:41

parameters4 = in2(4,:);
states2 = in1(2,:);
symbolicExpression = parameters4.*states2;
end
