function symbolicExpression = RepressilatorGenes_ODE_x_fun_1(in1,in2,in3)
%RepressilatorGenes_ODE_x_fun_1
%    symbolicExpression = RepressilatorGenes_ODE_x_fun_1(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:02:45

symbolicExpression = sparse([1,2,3,4,5,6,7,8,9,10,11,12],[1,1,1,1,1,1,1,1,1,1,1,1],[1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0],12,1);
end
