function symbolicExpression = RepressilatorGenes_7_2_fun_1(in1,in2)
%RepressilatorGenes_7_2_fun_1
%    symbolicExpression = RepressilatorGenes_7_2_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:40:44

states4 = in1(4,:);
symbolicExpression = states4;
end
