function symbolicExpression = RepressilatorGenes_s_fun_1(in1,in2)
%RepressilatorGenes_s_fun_1
%    symbolicExpression = RepressilatorGenes_s_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:02:41

states1 = in1(1,:);
states2 = in1(2,:);
states3 = in1(3,:);
states4 = in1(4,:);
states5 = in1(5,:);
states6 = in1(6,:);
states7 = in1(7,:);
states8 = in1(8,:);
states9 = in1(9,:);
symbolicExpression = reshape([0.0,0.0,states2,0.0,0.0,0.0,states5,0.0,0.0,0.0,states8,0.0,0.0,0.0,states1,0.0,0.0,0.0,states4,0.0,0.0,0.0,states7,0.0,(states1.*states6.*(states6-1.0).*(states6-2.0))./1.2e+1,0.0,0.0,0.0,(states4.*states9.*(states9-1.0).*(states9-2.0))./1.2e+1,0.0,0.0,0.0,(states3.*states7.*(states3-1.0).*(states3-2.0))./1.2e+1,0.0,0.0,0.0,0.0,states2,0.0,0.0,0.0,states5,0.0,0.0,0.0,states8,0.0,0.0,0.0,0.0,0.0,states3,0.0,0.0,0.0,states6,0.0,0.0,0.0,states9],[12,5]);
end
