function symbolicExpression = RepressilatorGenes_ODE_v_1_1_fun_1(t,in2,in3)
%RepressilatorGenes_ODE_v_1_1_fun_1
%    symbolicExpression = RepressilatorGenes_ODE_v_1_1_fun_1(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:02:47

varODEs2 = in3(:,2);
varODEs5 = in3(:,5);
varODEs8 = in3(:,8);
symbolicExpression = sparse([3,7,11],[1,1,1],[varODEs2,varODEs5,varODEs8],12,1);
end
