function symbolicExpression = RepressilatorGenes_10_fun_1(in1,in2)
%RepressilatorGenes_10_fun_1
%    symbolicExpression = RepressilatorGenes_10_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:40:43

parameters4 = in2(4,:);
states8 = in1(8,:);
symbolicExpression = parameters4.*states8;
end
