function symbolicExpression = RepressilatorGenes_11_1_fun_1(in1,in2)
%RepressilatorGenes_11_1_fun_1
%    symbolicExpression = RepressilatorGenes_11_1_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:40:45

states8 = in1(8,:);
symbolicExpression = states8;
end
