function symbolicExpression = RepressilatorGenes_6_fun_1(in1,in2)
%RepressilatorGenes_6_fun_1
%    symbolicExpression = RepressilatorGenes_6_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:02:41

parameters4 = in2(4,:);
states5 = in1(5,:);
symbolicExpression = parameters4.*states5;
end
