function symbolicExpression = RepressilatorGenes_7_fun_1(in1,in2)
%RepressilatorGenes_7_fun_1
%    symbolicExpression = RepressilatorGenes_7_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:40:43

parameters1 = in2(1,:);
parameters2 = in2(2,:);
states4 = in1(4,:);
states5 = in1(5,:);
symbolicExpression = parameters1.*states5+parameters2.*states4;
end
