function symbolicExpression = RepressilatorGenes_v_1_3_fun_1(t,in2)
%RepressilatorGenes_v_1_3_fun_1
%    symbolicExpression = RepressilatorGenes_v_1_3_fun_1(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:40:46

symbolicExpression = sparse([],[],[],12,1);
end
