function symbolicExpression = RepressilatorGenes_ODE_t_fun_1(t,in2,in3)
%RepressilatorGenes_ODE_t_fun_1
%    symbolicExpression = RepressilatorGenes_ODE_t_fun_1(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:02:45

parameters1 = in2(1,:);
parameters2 = in2(2,:);
parameters3 = in2(3,:);
parameters4 = in2(4,:);
parameters5 = in2(5,:);
varODEs1 = in3(:,1);
varODEs2 = in3(:,2);
varODEs3 = in3(:,3);
varODEs4 = in3(:,4);
varODEs5 = in3(:,5);
varODEs6 = in3(:,6);
varODEs7 = in3(:,7);
varODEs8 = in3(:,8);
varODEs9 = in3(:,9);
symbolicExpression = sparse([1,2,3,4,5,6,7,8,9,10,11,12],[1,1,1,1,1,1,1,1,1,1,1,1],[(parameters3.*varODEs1.*varODEs6.*(varODEs6-1.0).*(varODEs6-2.0))./1.2e+1,parameters4.*varODEs2,parameters1.*varODEs2+parameters2.*varODEs1,parameters5.*varODEs3,(parameters3.*varODEs4.*varODEs9.*(varODEs9-1.0).*(varODEs9-2.0))./1.2e+1,parameters4.*varODEs5,parameters1.*varODEs5+parameters2.*varODEs4,parameters5.*varODEs6,(parameters3.*varODEs3.*varODEs7.*(varODEs3-1.0).*(varODEs3-2.0))./1.2e+1,parameters4.*varODEs8,parameters1.*varODEs8+parameters2.*varODEs7,parameters5.*varODEs9],12,1);
end
