function symbolicExpression = RepressilatorGenes_4_fun_1(in1,in2)
%RepressilatorGenes_4_fun_1
%    symbolicExpression = RepressilatorGenes_4_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    21-Jan-2026 12:02:41

parameters5 = in2(5,:);
states3 = in1(3,:);
symbolicExpression = parameters5.*states3;
end
