function symbolicExpression = RepressilatorGenes_7_1_fun_1(in1,in2)
%RepressilatorGenes_7_1_fun_1
%    symbolicExpression = RepressilatorGenes_7_1_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:40:44

states5 = in1(5,:);
symbolicExpression = states5;
end
