function symbolicExpression = RepressilatorGenes_ODE_v_1_4_fun_1(t,in2,in3)
%RepressilatorGenes_ODE_v_1_4_fun_1
%    symbolicExpression = RepressilatorGenes_ODE_v_1_4_fun_1(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:40:49

varODEs2 = in3(:,2);
varODEs5 = in3(:,5);
varODEs8 = in3(:,8);
symbolicExpression = sparse([2,6,10],[1,1,1],[varODEs2,varODEs5,varODEs8],12,1);
end
