function symbolicExpression = RepressilatorGenes_ODE_3_fun_1(in1,in2)
%RepressilatorGenes_ODE_3_fun_1
%    symbolicExpression = RepressilatorGenes_ODE_3_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    05-Feb-2026 12:40:46

symbolicExpression = 1.0;
end
