function symbolicExpression = Sensitivities_ODE_2_fun_1(in1,in2)
%Sensitivities_ODE_2_fun_1
%    symbolicExpression = Sensitivities_ODE_2_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    15-Feb-2026 20:15:47

symbolicExpression = 1.0;
end
