function symbolicExpression = Sensitivities_1_2_fun_1(states1,in2)
%Sensitivities_1_2_fun_1
%    symbolicExpression = Sensitivities_1_2_fun_1(STATES1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    19-Feb-2026 23:55:14

symbolicExpression = 0.0;
end
