function symbolicExpression = Sensitivities_v_1_1_fun_1(t,in2)
%Sensitivities_v_1_1_fun_1
%    symbolicExpression = Sensitivities_v_1_1_fun_1(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    19-Feb-2026 01:54:00

symbolicExpression = sparse([1],[1],[1.0],2,1);
end
