function symbolicExpression = Sensitivities_t_fun_1(t,in2)
%Sensitivities_t_fun_1
%    symbolicExpression = Sensitivities_t_fun_1(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    19-Feb-2026 23:55:14

parameters1 = in2(1,:);
symbolicExpression = sparse([1,2],[1,1],[parameters1,1.0],2,1);
end
