function symbolicExpression = Sensitivities_s_fun_1(states1,in2)
%Sensitivities_s_fun_1
%    symbolicExpression = Sensitivities_s_fun_1(STATES1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    15-Feb-2026 20:15:47

symbolicExpression = reshape([0.0,0.0,0.0,states1],[2,2]);
end
