function symbolicExpression = Sensitivities_v_1_2_fun_1(t,in2)
%Sensitivities_v_1_2_fun_1
%    symbolicExpression = Sensitivities_v_1_2_fun_1(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    15-Feb-2026 20:15:47

symbolicExpression = sparse([],[],[],2,1);
end
