function symbolicExpression = Sensitivities_ODE_1_fun_1(in1,in2)
%Sensitivities_ODE_1_fun_1
%    symbolicExpression = Sensitivities_ODE_1_fun_1(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    18-Feb-2026 13:25:31

symbolicExpression = 1.0;
end
