function symbolicExpression = Sensitivities_x_fun_1(states1,in2)
%Sensitivities_x_fun_1
%    symbolicExpression = Sensitivities_x_fun_1(STATES1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    24-Feb-2026 14:40:24

parameters2 = in2(2,:);
symbolicExpression = [1.0;parameters2.*states1];
end
