function symbolicExpression = Sensitivities_ODE_x_fun_1(in1,in2,varODEs1)
%Sensitivities_ODE_x_fun_1
%    symbolicExpression = Sensitivities_ODE_x_fun_1(IN1,IN2,varODEs1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    24-Feb-2026 14:40:24

symbolicExpression = sparse([1,2],[1,1],[1.0,1.0],2,1);
end
