function symbolicExpression = Sensitivities_2_1_fun_1(states1,in2)
%Sensitivities_2_1_fun_1
%    symbolicExpression = Sensitivities_2_1_fun_1(STATES1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    04-Feb-2026 23:43:23

symbolicExpression = 0.0;
end
