function symbolicExpression = Sensitivities_2_1_fun_1(states1,in2)
%Sensitivities_2_1_fun_1
%    symbolicExpression = Sensitivities_2_1_fun_1(STATES1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    24-Feb-2026 14:40:24

symbolicExpression = 0.0;
end
