function symbolicExpression = Sensitivities_ODE_v_1_2_fun_1(t,in2,varODEs1)
%Sensitivities_ODE_v_1_2_fun_1
%    symbolicExpression = Sensitivities_ODE_v_1_2_fun_1(T,IN2,varODEs1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    19-Feb-2026 00:46:51

symbolicExpression = sparse([2],[1],[varODEs1],2,1);
end
