function symbolicExpression = Sensitivities_2_fun_1(states1,in2)
%Sensitivities_2_fun_1
%    symbolicExpression = Sensitivities_2_fun_1(STATES1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    19-Feb-2026 23:55:14

parameters2 = in2(2,:);
symbolicExpression = parameters2.*states1;
end
