function symbolicExpression = Sensitivities_v_1_1_fun_1(t,in2)
%Sensitivities_v_1_1_fun_1
%    symbolicExpression = Sensitivities_v_1_1_fun_1(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    18-Feb-2026 13:25:31

symbolicExpression = sparse([1],[1],[1.0],2,1);
end
