function symbolicExpression = Sensitivities_ODE_s_fun_1(in1,in2,varODEs1)
%Sensitivities_ODE_s_fun_1
%    symbolicExpression = Sensitivities_ODE_s_fun_1(IN1,IN2,varODEs1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    18-Feb-2026 13:25:32

symbolicExpression = sparse([],[],[],2,2);
end
